name = "physics-problem-bank-worker"
main = "src/index.js"
compatibility_date = "2026-01-01"

[[kv_namespaces]]
binding = "PROBLEM_KEYS"
id = "0354a1552c4b495fba9d2f04b82787ca"

[[r2_buckets]]
binding = "PROTECTED_PDFS"
bucket_name = "physics-problem-bank-protected"
